In [1]:
import pandas as pd
import numpy as np

In [27]:
add_sum = 100_000
proc = 1.01333333
cur_sum = add_sum
cnt_month = 12 * 30
for i in range(1, cnt_month):
    cur_sum *= proc
    print(i, cur_sum)
    cur_sum += add_sum

1 101333.333
2 204017.77676888887
3 308071.3461124148
4 413512.29603367584
5 520359.12493575056
6 628630.5778670303
7 738345.6498098221
8 849523.589012801
9 962183.900367893
10 1076346.3488321854
11 1192030.96289546
12 1309258.038093963
13 1428048.1405710224
14 1548422.1106851422
15 1670401.0666662038
16 1794006.4083204162
17 1919259.820784667
18 2046183.27833093
19 2174799.048221398
20 2305129.69461502
21 2437198.0825261213
22 2571027.3818358094
23 2706641.0713568623
24 2844062.942952817
25 2983317.105711978
26 3124427.9901770805
27 3267420.352631348
28 3412319.2794416985
29 3559150.191459857
30 3707938.8484821543
31 3858711.353768787
32 4011494.158623333
33 4166314.0670333304
34 4323198.240372728
35 4482174.202167037
36 4643269.842922017
37 4806513.425016745
38 4971933.587661924
39 5139559.351924304
40 5309420.125818097
41 5481545.709464272
42 5655966.300318643
43 5832712.498469671
44 6011815.312006892
45 6193306.1624609325
46 6377216.890316058
47 6563579.760596216
48 6752427.468525566
49 6943793.145264482
50 7137710.363722032
51 7334213.144445958
52 7533335.961591193
53 7735113.748967957
54 7939581.906170484
55 8146776.304787484
56 8356733.294695396
57 8569489.710435558
58 8785082.8776764
59 9003550.61976181
60 9224931.264346799
61 9449263.650121652
62 9676587.133625729
63 9906941.596152116
64 10140367.450744338
65 10376905.649286373
66 10616597.689687172
67 10859485.623161009
68 11105612.06160487
69 11355020.185074229
70 11607753.749358485
71 11863857.09365742
72 12123375.148359995
73 12386353.442926878
74 12652838.113878058
75 12922875.912886972
76 13196514.214982545
77 13473801.026860598
78 13754784.99530607
79 14039515.415727535
80 14328042.240805518
81 14620416.089256117
82 14916688.254711479
83 15216910.714718672
84 15521136.139858551
85 15829417.902986212
86 16141810.088594636
87 16458367.502303198
88 16779145.680472683
89 17104200.8999485
90 17433590.18793381
91 17767371.331994295
92 18105602.890196316
93 18448344.201380257
94 18795655.395570848
95 19147597.404526275
96 19504231.972427968
97 19865621.666712902
98 20231829.889050335
99 20602920.886464905
100 20978959.762608036
101 21360012.48917961
102 21746145.917501964
103 22137427.79024817
104 22533926.75332672
105 22935712.367924657
106 23342855.12271128
107 23755426.44620458
108 24173498.719302554
109 24597145.287981592
110 25026440.476164196
111 25461459.59875825
112 25902278.974870164
113 26348975.94119417
114 26801628.86558017
115 27260317.16078248
116 27725121.298391856
117 28196122.822953343
118 28673404.36627231
119 29157049.66191126
120 29647143.559879914
121 30143772.04152117
122 30647022.234595545
123 31156982.428566746
124 31673742.09009103
125 32197391.878713105
126 32728023.662771307
127 33265730.535514846
128 33810606.83143594
129 34362748.14281973
130 34922251.33651484
131 35489214.57092753
132 36063737.31324252
133 36645920.356873296
134 37235865.839145206
135 37833677.25921426
136 38439459.49622486
137 39053318.82770966
138 39675362.94823473
139 40305700.98829332
140 40944443.533451565
141 41591702.64374944
142 42247591.873360425
143 42912226.29051326
144 43585722.49767935
145 44268198.652029335
146 44959774.4861624
147 45660571.329111986
148 46370712.127631575
149 47090321.46776429
150 47819525.59670007
151 48558452.444924325
152 49307231.64866181
153 50065994.57261986
154 50834874.33303481
155 51614005.8210257
156 52403525.72625936
157 53203572.560931064
158 54014286.6840649
159 54835810.326138146
160 55668287.61403395
161 56511864.59632678
162 57366689.268904924
163 58232911.60093469
164 59110683.56117079
165 60000159.14461745
166 60901494.399545155
167 61814847.454867445
168 62740378.547882855
169 63678250.0523867
170 64628626.50715769
171 65591674.64482437
172 66567563.42111645
173 67556464.04450613
174 68558550.00624467
175 69573997.11079943
176 70602983.50669678
177 71645689.71777612
178 72702298.67486084
179 73772995.74785133
180 74857968.77824603
181 75957408.11209609
182 77071506.63339934
183 78200459.79793964
184 79344465.66757731
185 80503724.94499679
186 81678441.00891766
187 82868819.9497751
188 84075070.60587604
189 85297404.60003749
190 86536036.3767133
191 87791183.23961604
192 89063065.3898403
193 90351905.96449463
194 91657931.0758482
195 92981369.85099974
196 94322454.47207518
197 95681420.21696134
198 97058505.50058275
199 98453951.91672884
200 99868004.28043872
201 101300910.67095123
202 102752922.47522755
203 104224294.43205418
204 105715284.67673393
205 107226154.78637277
206 108757169.82577056
207 110308598.3939236
208 111880712.67114726
209 113473788.46682684
210 115088105.26780525
211 116723946.28741564
212 118381598.51516803
213 120061352.76709828
214 121763503.73678842
215 123488350.04706725
216 125236194.30240032
217 127007343.14197835
218 128802107.2935136
219 130620801.62775342
220 132463745.2137208
221 134331261.37469125
222 136223677.74491626
223 138141326.3271029
224 140084543.55065987
225 142053670.3307202
226 144049052.1279509
227 146071039.00916007
228 148119985.70871207
229 150196251.69076163
230 152300201.21231762
231 154432203.38714784
232 156592632.25053582
233 158781866.82490087
234 161000291.18629333
235 163248294.53177628
236 165526271.24770564
237 167834620.97892082
238 170173748.6988577
239 172544064.78059664
240 174945985.06885773
241 177379930.9529559
242 179846329.44072887
243 182345613.23345083
244 184878220.8017448
245 187444596.46250734
246 190045190.45685878
247 192680459.02913293
248 195350864.50691986
249 198056875.38217592
250 200798966.39341536
251 203577618.60899767
252 206393319.5115256
253 209246563.0833682
254 212137849.89332458
255 215067687.18444276
256 218036588.96300972
257 221045076.0887279
258 224093676.36609402
259 227182924.63699636
260 230313362.87454656
261 233485540.27816263
262 236700013.36991966
263 239957346.09218523
264 243258109.90655655
265 246602883.89411694
266 249992254.8570289
267 253426817.4214818
268 256907174.14201215
269 260433935.60721508
270 264007720.54686484
271 267629155.940464
272 271298877.12723964
273 275017527.9176066
274 278785760.70611626
275 282604236.5859119
276 286473625.46471
277 290394606.1823274
278 294367866.6297764
279 298394103.8699472
280 302474024.2598995
281 306608343.57478476
282 310797787.13342077
283 315043089.92554045
284 319344996.7407374
285 323704262.29913056
286 328121651.3837714
287 332597938.9748162
288 337133910.3854873
289 341730361.39984745
290 346388098.4124109
291 351107938.5696161
292 355890709.9131845
293 360737251.5253913
294 365648413.67627233
295 370625057.9727946
296 375668057.510015
297 380778297.02425504
298 385956673.04831743
299 391204094.0687728
300 396521480.6853428
301 401909765.7724091
302 407369894.64267534
303 412902825.2130114
304 418509528.1725088
305 424190987.15277714
306 429948198.9005109
307 435782173.45235705
308 441693934.3121146
309 447684518.63029635
310 453754977.3860853
311 459906375.5717165
312 466139792.3793181
313 472456321.39024305
314 478857070.7669252
315 485343163.447294
316 491915737.3417807
317 498575945.532952
318 505324956.4778049
319 512163954.21275914
320 519094138.5613828
321 526116725.34488744
322 533232946.5954302
323 540444050.7722595
324 547751302.9807428
325 555155985.1943151
326 562659396.479386
327 570262853.2232465
328 577967689.3650136
329 585775256.6296549
330 593686924.7651328
331 601704081.7827115
332 609828134.2004673
333 618060507.2900465
334 626402645.326712
335 634856011.842726
336 643422089.884109
337 652102382.2708235
338 660898411.8604265
339 669811721.8152375
340 678843875.8730683
341 687996458.621563
342 697271075.7761956
343 706669354.4619747
344 716192943.4989033
345 725843513.6912456
346 735622758.1206505
347 745532392.4431834
348 755574155.1903179
349 765749808.0739416
350 776061136.2954282
351 786509948.8588301
352 797098078.888248
353 807827383.9494311
354 818699746.3756655
355 829717073.5980086
356 840881298.4799252
357 852194379.6563865
358 863658301.8774904
359 875275076.3566626

In [ ]:
875_275_076

## Обрабатываем silver-разметку с помощью GPT 5.5, Claude Sonnet 4.5 и Opus 4.6. Достаем самый частый класс из трех

In [2]:
df = pd.read_excel("data/app_reviews_ru_only_text_AI_LABELED.xlsx")
df

,app_name,text,rating,thumbs_up_count,label_silver_GPT,label_silver_CLAUDE_LOW,label_silver_CLAUDE_HIGH,label_gold,summary_gold
0,Telegram,Приложение сломано на Android 16. Бесконечное ...,1,0,bug_report,bug_report,bug_report,NaN,NaN
1,Telegram,приложение супер.🔥 одно из любимых.всегда смот...,5,0,bug_report,bug_report,bug_report,NaN,NaN
2,Telegram,много визуальных багов после редизайна,3,0,bug_report,bug_report,bug_report,NaN,NaN
3,Telegram,Ван Пис! Ван Пис существует!,5,0,user_experience,user_experience,user_experience,NaN,NaN
4,Telegram,хорошее,5,0,rating,rating,rating,NaN,NaN
...,...,...,...,...,...,...,...,...,...
3258,Avito,Быстрый профессиональный и качественный резуль...,5,0,user_experience,user_experience,user_experience,NaN,NaN
3259,Avito,"Я сейчас в шоке от этого авито, раньше когда я...",1,0,user_experience,user_experience,user_experience,NaN,NaN
3260,Avito,Отвратительный сайт. Фильтры не справляются с ...,1,0,user_experience,user_experience,user_experience,NaN,NaN
3261,Avito,продал быстро,5,0,user_experience,rating,user_experience,NaN,NaN
3262,Avito,Вау. Надо же было настолько испортить в поиске...,1,248,user_experience,user_experience,user_experience,NaN,NaN

In [3]:
values = df[["label_silver_GPT", "label_silver_CLAUDE_LOW" ,"label_silver_CLAUDE_HIGH"]].values

In [6]:
values.tolist()

[['bug_report', 'bug_report', 'bug_report'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['rating', 'rating', 'rating'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['user_experience', 'rating', 'user_experience'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['bug_report', 'bug_report', 'user_experience'],
 ['bug_report', 'bug_report', 'user_experience'],
 ['rating', 'rating', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['rating', 'user_experience', 'user_experience'],
 ['bug_report', 'bug_report', 'feature_request'],
 ['feature_request', 'user_experience', 'user_experience'],
 ['bug_report', 'user_experience', 'bug_report'],
 ['rating', 'rating', 'user_experience'],
 ['bug_report', 'user_experience', 'user_experience'],
 ['feature_request', 'feature_request', 'feature_request'],
 ['rating', 'rating', 'user_experience'],
 ['rating', 'rating', 'user_experience'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['feature_request', 'feature_request', 'feature_request'],
 ['bug_report', 'user_experience', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['bug_report', 'user_experience', 'user_experience'],
 ['bug_report', 'bug_report', 'feature_request'],
 ['feature_request', 'feature_request', 'feature_request'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['rating', 'rating', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['rating', 'rating', 'user_experience'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['rating', 'rating', 'feature_request'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['feature_request', 'user_experience', 'user_experience'],
 ['rating', 'rating', 'user_experience'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['rating', 'rating', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['rating', 'rating', 'user_experience'],
 ['bug_report', 'bug_report', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['rating', 'rating', 'user_experience'],
 ['rating', 'rating', 'user_experience'],
 ['rating', 'feature_request', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['bug_report', 'user_experience', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['bug_report', 'user_experience', 'bug_report'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['user_experience', 'rating', 'user_experience'],
 ['user_experience', 'user_experience', 'bug_report'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['rating', 'rating', 'feature_request'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['user_experience', 'rating', 'user_experience'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['user_experience', 'rating', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['rating', 'rating', 'rating'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['rating', 'rating', 'rating'],
 ['rating', 'user_experience', 'user_experience'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['bug_report', 'user_experience', 'bug_report'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['rating', 'rating', 'user_experience'],
 ['rating', 'rating', 'user_experience'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['bug_report', 'bug_report', 'user_experience'],
 ['bug_report', 'user_experience', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['rating', 'rating', 'user_experience'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['rating', 'rating', 'rating'],
 ['user_experience', 'rating', 'user_experience'],
 ['rating', 'rating', 'user_experience'],
 ['rating', 'rating', 'user_experience'],
 ['rating', 'rating', 'user_experience'],
 ['rating', 'rating', 'rating'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['user_experience', 'rating', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['rating', 'rating', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['rating', 'rating', 'user_experience'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['rating', 'rating', 'rating'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['rating', 'rating', 'user_experience'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['feature_request', 'user_experience', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['rating', 'rating', 'rating'],
 ['user_experience', 'rating', 'user_experience'],
 ['rating', 'rating', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['user_experience', 'bug_report', 'bug_report'],
 ['bug_report', 'rating', 'user_experience'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['rating', 'rating', 'user_experience'],
 ['user_experience', 'rating', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['bug_report', 'user_experience', 'bug_report'],
 ['rating', 'rating', 'user_experience'],
 ['bug_report', 'rating', 'user_experience'],
 ['feature_request', 'feature_request', 'feature_request'],
 ['rating', 'rating', 'user_experience'],
 ['user_experience', 'user_experience', 'bug_report'],
 ['rating', 'rating', 'user_experience'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['user_experience', 'bug_report', 'user_experience'],
 ['bug_report', 'user_experience', 'bug_report'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['user_experience', 'rating', 'user_experience'],
 ['feature_request', 'feature_request', 'feature_request'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['feature_request', 'feature_request', 'feature_request'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['rating', 'rating', 'user_experience'],
 ['bug_report', 'bug_report', 'user_experience'],
 ['user_experience', 'user_experience', 'feature_request'],
 ['user_experience', 'bug_report', 'bug_report'],
 ['rating', 'rating', 'user_experience'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['rating', 'rating', 'user_experience'],
 ['rating', 'rating', 'user_experience'],
 ['bug_report', 'user_experience', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['feature_request', 'feature_request', 'feature_request'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['bug_report', 'bug_report', 'user_experience'],
 ['rating', 'rating', 'user_experience'],
 ['bug_report', 'user_experience', 'bug_report'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['rating', 'rating', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['rating', 'user_experience', 'user_experience'],
 ['feature_request', 'feature_request', 'feature_request'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['bug_report', 'user_experience', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['bug_report', 'user_experience', 'bug_report'],
 ['user_experience', 'user_experience', 'bug_report'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['bug_report', 'user_experience', 'user_experience'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['rating', 'rating', 'rating'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['feature_request', 'feature_request', 'feature_request'],
 ['bug_report', 'user_experience', 'user_experience'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['rating', 'rating', 'user_experience'],
 ['bug_report', 'rating', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['user_experience', 'rating', 'user_experience'],
 ['bug_report', 'user_experience', 'bug_report'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['user_experience', 'rating', 'user_experience'],
 ['rating', 'rating', 'user_experience'],
 ['bug_report', 'rating', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['rating', 'rating', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['feature_request', 'rating', 'user_experience'],
 ['user_experience', 'user_experience', 'bug_report'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['rating', 'rating', 'rating'],
 ['bug_report', 'rating', 'user_experience'],
 ['user_experience', 'bug_report', 'bug_report'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['bug_report', 'user_experience', 'bug_report'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['feature_request', 'feature_request', 'feature_request'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['rating', 'rating', 'user_experience'],
 ['bug_report', 'user_experience', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['bug_report', 'user_experience', 'user_experience'],
 ['user_experience', 'rating', 'user_experience'],
 ['bug_report', 'user_experience', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['user_experience', 'user_experience', 'bug_report'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['bug_report', 'user_experience', 'bug_report'],
 ['rating', 'rating', 'user_experience'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['user_experience', 'rating', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['rating', 'rating', 'user_experience'],
 ['user_experience', 'rating', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['user_experience', 'rating', 'user_experience'],
 ['rating', 'rating', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['bug_report', 'user_experience', 'user_experience'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['user_experience', 'feature_request', 'user_experience'],
 ['rating', 'rating', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['rating', 'rating', 'user_experience'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['user_experience', 'rating', 'user_experience'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['user_experience', 'bug_report', 'bug_report'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['rating', 'rating', 'user_experience'],
 ['bug_report', 'bug_report', 'feature_request'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['rating', 'rating', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['user_experience', 'rating', 'user_experience'],
 ['bug_report', 'rating', 'user_experience'],
 ['rating', 'rating', 'user_experience'],
 ['user_experience', 'rating', 'user_experience'],
 ['bug_report', 'rating', 'user_experience'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['bug_report', 'user_experience', 'user_experience'],
 ['bug_report', 'bug_report', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['rating', 'rating', 'user_experience'],
 ['user_experience', 'rating', 'user_experience'],
 ['user_experience', 'rating', 'user_experience'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['bug_report', 'user_experience', 'user_experience'],
 ['feature_request', 'user_experience', 'user_experience'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['user_experience', 'rating', 'user_experience'],
 ['rating', 'rating', 'user_experience'],
 ['bug_report', 'rating', 'user_experience'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['rating', 'rating', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['rating', 'rating', 'user_experience'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['rating', 'rating', 'user_experience'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['user_experience', 'rating', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['bug_report', 'user_experience', 'bug_report'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['rating', 'rating', 'user_experience'],
 ['feature_request', 'bug_report', 'feature_request'],
 ['bug_report', 'rating', 'bug_report'],
 ['rating', 'rating', 'user_experience'],
 ['rating', 'user_experience', 'user_experience'],
 ['rating', 'user_experience', 'user_experience'],
 ['bug_report', 'user_experience', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['rating', 'rating', 'user_experience'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['user_experience', 'user_experience', 'bug_report'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['rating', 'rating', 'user_experience'],
 ['bug_report', 'user_experience', 'user_experience'],
 ['bug_report', 'user_experience', 'bug_report'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['bug_report', 'user_experience', 'user_experience'],
 ['rating', 'rating', 'user_experience'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['feature_request', 'feature_request', 'feature_request'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['rating', 'rating', 'user_experience'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['rating', 'rating', 'user_experience'],
 ['user_experience', 'rating', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['rating', 'rating', 'feature_request'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['user_experience', 'rating', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['rating', 'rating', 'rating'],
 ['user_experience', 'rating', 'user_experience'],
 ['rating', 'rating', 'user_experience'],
 ['bug_report', 'user_experience', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['rating', 'rating', 'user_experience'],
 ['bug_report', 'user_experience', 'user_experience'],
 ['rating', 'rating', 'user_experience'],
 ['rating', 'rating', 'user_experience'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['user_experience', 'rating', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['bug_report', 'rating', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['rating', 'rating', 'user_experience'],
 ['bug_report', 'bug_report', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['rating', 'rating', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['rating', 'rating', 'user_experience'],
 ['bug_report', 'bug_report', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['rating', 'rating', 'user_experience'],
 ['feature_request', 'user_experience', 'user_experience'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['bug_report', 'bug_report', 'bug_report'],
 ['bug_report', 'user_experience', 'bug_report'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['rating', 'rating', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['rating', 'rating', 'user_experience'],
 ['feature_request', 'feature_request', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],
 ['user_experience', 'user_experience', 'user_experience'],

In [7]:
df["ALL_AI_LABELS"] = values.tolist()

In [9]:
from collections import Counter


def extract_most_frequent_word(series):
    """
    Возвращает Series с самым частым словом из списков в исходной колонке.
    """
    def get_top_word(word_list):
        # Проверка на корректный тип и непустой список
        if not isinstance(word_list, list) or len(word_list) == 0:
            return np.nan
        # Counter.most_common(1) -> [('слово', count)]
        return Counter(word_list).most_common(1)[0][0]
        
    return series.apply(get_top_word)

In [10]:
df['lable_silver_common_AI'] = extract_most_frequent_word(df["ALL_AI_LABELS"])

In [12]:
df = df.drop(columns=["label_silver_GPT", "label_silver_CLAUDE_LOW" ,"label_silver_CLAUDE_HIGH", "ALL_AI_LABELS"])

In [13]:
df

,app_name,text,rating,thumbs_up_count,label_gold,summary_gold,lable_silver_common_AI
0,Telegram,Приложение сломано на Android 16. Бесконечное ...,1,0,NaN,NaN,bug_report
1,Telegram,приложение супер.🔥 одно из любимых.всегда смот...,5,0,NaN,NaN,bug_report
2,Telegram,много визуальных багов после редизайна,3,0,NaN,NaN,bug_report
3,Telegram,Ван Пис! Ван Пис существует!,5,0,NaN,NaN,user_experience
4,Telegram,хорошее,5,0,NaN,NaN,rating
...,...,...,...,...,...,...,...
3258,Avito,Быстрый профессиональный и качественный резуль...,5,0,NaN,NaN,user_experience
3259,Avito,"Я сейчас в шоке от этого авито, раньше когда я...",1,0,NaN,NaN,user_experience
3260,Avito,Отвратительный сайт. Фильтры не справляются с ...,1,0,NaN,NaN,user_experience
3261,Avito,продал быстро,5,0,NaN,NaN,user_experience
3262,Avito,Вау. Надо же было настолько испортить в поиске...,1,248,NaN,NaN,user_experience

In [ ]:
df.to_excel("data/app_reviews_ru_only_text_AI_LABELED_PREPARED.xlsx")

In [ ]:
df.to_csv("data/app_reviews_ru_only_text_AI_LABELED_PREPARED.csv")

## Обрабатываем отзывы

In [15]:
import re
import pandas as pd


def normalize_spaces(text: str) -> str:
    text = re.sub(r"\s+", " ", text)
    return text.strip()


def remove_html(text: str) -> str:
    return re.sub(r"<.*?>", " ", text)


def mask_personal_data(text: str) -> str:
    # email
    text = re.sub(
        r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b",
        "<EMAIL>",
        text
    )

    # phone numbers, rough version
    text = re.sub(
        r"(\+7|8)?[\s\-()]?\d{3}[\s\-()]?\d{3}[\s\-()]?\d{2}[\s\-()]?\d{2}",
        "<PHONE>",
        text
    )

    # urls
    text = re.sub(
        r"(https?://\S+|www\.\S+)",
        "<URL>",
        text
    )

    return text


def reduce_repeated_chars(text: str) -> str:
    # "круууутооооо" -> "круутоо"
    # Не режем до одной буквы, чтобы сохранить эмоциональность
    return re.sub(r"(.)\1{3,}", r"\1\1", text)


def has_enough_cyrillic(text: str, threshold: float = 0.5) -> bool:
    letters = re.findall(r"[A-Za-zА-Яа-яЁё]", text)
    if not letters:
        return False

    cyrillic = re.findall(r"[А-Яа-яЁё]", text)
    return len(cyrillic) / len(letters) >= threshold


def clean_review_text(text: str) -> str:
    if not isinstance(text, str):
        return ""

    text = remove_html(text)
    text = mask_personal_data(text)
    text = reduce_repeated_chars(text)
    text = normalize_spaces(text)

    return text


def make_dedup_key(text: str) -> str:
    text = text.lower()
    text = re.sub(r"[^\wа-яё]+", " ", text, flags=re.IGNORECASE)
    text = re.sub(r"\s+", " ", text)
    return text.strip()

In [ ]:
df_test = pd.read_excel("data/app_reviews_ru_only_text_AI_LABELED_PREPARED.xlsx")

# Сохраняем оригинал
df_test["review_text_raw"] = df_test["text"].astype(str)

# Создаём очищенный текст
df_test["review_text_clean"] = df_test["review_text_raw"].apply(clean_review_text)

# Удаляем пустые и слишком короткие
df_test = df_test[df_test["review_text_clean"].str.len() >= 3]

# Фильтр по русскому языку
df_test = df_test[df_test["review_text_clean"].apply(has_enough_cyrillic)]

# Удаляем дубликаты
df_test["dedup_key"] = df_test["review_text_clean"].apply(make_dedup_key)
df_test = df_test.drop_duplicates(subset=["dedup_key"])

# Удаляем временную колонку
df_test = df_test.drop(columns=["dedup_key"])

# Добавляем поля для ручной разметки
df_test["label_gold"] = ""
df_test["summary_gold"] = ""
df_test["comment"] = ""


# df_test.to_csv("app_reviews_ru_for_annotation.csv", index=False, encoding="utf-8-sig")
df_test.to_excel("data/app_reviews_ru_AI_LABELED_for_annotation.xlsx", index=False)

print(f"Готово. Осталось отзывов: {len(df)}")

Готово. Осталось отзывов: 3263